[package]
name = "crypto_api_chachapoly"
version = "0.5.0"
edition = "2018"
authors = ["Keziah Biermann <development@kizzycode.de>"]
description = "An implementation of ChaCha20-IETF, Poly1305 and ChachaPoly-IETF for `crypto_api`"
k