[package]
name = "fuzz"
version = "0.1.0"
authors = ["Keziah Biermann <development@kizzycode.de>"]
edition = "2018"


[features]
default = []


[dependencies]
crypto_api_chachapoly = { path = "../" }
sodiumoxide = "^0.2"
num_c